### ISSUE TITLE
how to ues in vue

### ISSUE THREAD

**Issue by White-Emperor-Sword** [zachcp/simple-rdkitjs#1]
i want to ues rdkit.js in vue，without npm how to use it？

**Comment by zachcp** [comment]
Take a look in demo.html for how to interact with the JS/WASM files. Your Vue component would handle all of the UI and you would call in to the `RDKitModule` for access to RDKit functions. 

 I don't know Vue but I would start by writing components that mimic the behavior of the vanilla HTML+JS in the demo.html file.

**Comment by White-Emperor-Sword** [comment]
I don't quite understand that there should be an instantiation process before using rdkitmodule to call functions. How should this be introduced? And what does "OnRuntimeInitialized" mean in demo?

**Comment by zachcp** [comment]
You need `onRuntimeInitialized`. If you open webdevelop tools while visiting the [live page](https://zachcp.github.io/simple-rdkitjs/) you will have access to the `RDKitModule` functions in your browser console. These are JS functions backed by WASM compiled from C.

You can call in to the RDKitModule once its been initialized.  Beyond that, you can choose to handle the outputs as you like.




![image](https://user-images.githubusercontent.com/1260667/107403245-e2761d00-6ad2-11eb-8505-6f7710b3aff4.png)
